version: '3.4'

services:
  pisec.api:
    container_name: pisec.api
    image: ${DOCKER_REGISTRY-}pisecapi
    build:
      context: .
      dockerfile: PiSec.Api/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"

  pisec.db:
    container_name: pisec.db
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: PiSecDB
    ports:
      - "3306:3306"
    volumes:
      - ./.containers/pisec-db:/var/lib/mysql
